### PR TITLE
Minor corrections to phrasing/spelling.

### PR DESCRIPTION
**Pull request by whackablemole**
Just some small corrections to spellings and added correct plurals to the units in the password strength analyser.

### CODE REVIEW

**Review by CorentinTh — APPROVED** [review]
Hi @whackablemole !
Thank you for this fix 🙏🏻

**Comment by CorentinTh** [comment]
Their is an issue with e2e test, can you please replace 
```javascript
// in src/tools/password-strength-analyser/password-strength-analyser.e2e.spec.ts
// replace :
    expect(crackDuration).toEqual('15,091 milleniums, 3 centurys');
// with :
    expect(crackDuration).toEqual('15,091 millennia, 3 centuries');
```

I can't edit your fork to do it myself :/

**Comment by whackablemole** [comment]
Sorry about that! I had set it so that you could edit it so am not sure why
that wasn't working. I have made that change now. :)

**Comment by whackablemole** [comment]
> Their is an issue with e2e test, can you please replace
> 
> ```js
> // in src/tools/password-strength-analyser/password-strength-analyser.e2e.spec.ts
> // replace :
>     expect(crackDuration).toEqual('15,091 milleniums, 3 centurys');
> // with :
>     expect(crackDuration).toEqual('15,091 millennia, 3 centuries');
> ```
> 
> I can't edit your fork to do it myself :/

Sorry, I thought I had set it properly so you could edit as well, but I am new to pull requests. Just really love these tools so wanted to get involved. :)

**Comment by CorentinTh** [comment]
No problem, thanks for the contribution 💪🏻

**Pull request merged**
