### PR TITLE
feat(json-diff): add new tool to get the diff of two given JSONs

### PR DESCRIPTION
**Pull request by cgoIT**
I look forward to your feedback. If it's too much garbage, then please just delete the PR ;)

### CODE REVIEW

**Comment by CorentinTh** [comment]
I planned to make this kind of tools from scratch, it's quite easy to diffs two objects, and we can have more control of the output display instead of needind an html sanitizer (which I dont really want in the app, it's just a v-html with extra steps

What do you think?

**Comment by cgoIT** [comment]
Hi @CorentinTh,

I know what you mean. That the reason why I at least integrated the santize-html part. ;)

IMO this feature could be split into two logical parts: the diffing and the visual representation of the diff result. For the first part I also had a look at microdiff library, which gives a very nice result and is quite lightweight I think. Personally I tend to use existing, maintained libraries over reinventing the wheel. At least in the Java world where I come from. But I agree: If you only use a little amount of the functionality of an existing library it might be a good idea to implement this part on your own.
I think for the visual representation there is nearly no way to omit html and some css. But I'd be happy to see other options/ideas. ;)

BTW: is there any way to prevent the tree shaking for certain parts of a vite based application? The tree shaking is - at least I think so - the only reason why I had to import a static css.

**Comment by CorentinTh** [comment]
Yeah, I sure don't want to reinvent the wheel, but I'm kind of afraid of the future size of the app bundle with that many dependencies.

Would that be okay for you if I try to remake this tool without needing raw HTML rendering? If it's too hard to make, we'll fallback on your approach

**Comment by cgoIT** [comment]
Hi,

in any case: yes! This gives me the great opportunity to learn how to do it better or differently.

**Comment by CorentinTh** [comment]
Made it !
You can look at #377

I used a custom recurcive data structure to iterate and prevent v-html

```js
// for those jsons :
const obj = { a: 1, b: 2 };
const newObj = { a: 1, b: 2, c: 3 };

// we get :
{
  key: '',
  type: 'object',
  children: [
    {
      key: 'a',
      type: 'value',
      value: 1,
      oldValue: 1,
      status: 'unchanged',
    },
    {
      key: 'b',
      type: 'value',
      value: 2,
      oldValue: 2,
      status: 'unchanged',
    },
    {
      key: 'c',
      type: 'value',
      value: 3,
      oldValue: undefined,
      status: 'added',
    },
  ],
  oldValue: { a: 1, b: 2 },
  value: { a: 1, b: 2, c: 3 },
  status: 'children-updated',
}
```

**Comment by CorentinTh** [comment]
Thanks anyway for taking the time to make this PR 🙏🏻

**Pull request closed without merging**
