### PR TITLE
fix: allow app to run in a subfolder via BASE_URL

### LINKED ISSUE #356: [NEW FEAT.] - Allow URL Base configuration (Docker)
**Which tool is impacted?**
IT-Tool as a whole.

**Describe the solution you'd like**
Allow the configuration of an URL Base on the docker image.
That will enable to configure the tool behind a proxy using a "subfolder" configuration (and not a subdomain).
Currently, if this configuration is done (e.g. https://mydomain.com/it-tools ) the tool is not working as the call to js (and css) assume an absolute path (redacted, just in case):
```
<script type="module" crossorigin src="/assets/index.***.js"></script>
<link rel="stylesheet" href="/assets/index.***.css">
```

**Is their example of this tool in the wild?**
Other apps offer this configuration.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by rmtsrc**
Closes #356 #423

Some services such as GitHub pages will host the app in a subfolder such as `https://<username>.github.io/<repo-name>/`

Currently when trying to self host it-tools via [a GitHub pages action](https://github.com/rmtsrc/it-tools/blob/main/.github/workflows/deploy-pages.yaml) the [`BASE_URL`](https://github.com/CorentinTh/it-tools/blob/main/src/config.ts#L17-L22) environment variable was ignored and the `index.html` file was requesting JavaScript and CSS from `/assets/...`, rather than `/<subfolder>/assets/...`

This PR allows the `BASE_URL` to be used to correctly set the full URL of the app allowing both `/` and `/<subfolder>/`

### CODE REVIEW

**Review by CorentinTh — CHANGES_REQUESTED** [review]
Hi!
Thank you for the PR and tackling those issues 🙏🏻 

Just a small request:
- Please import the `config` from `scr/config.ts` and use `config.app.baseUrl`

**Comment by rmtsrc** [comment]
> Hi! Thank you for the PR and tackling those issues 🙏🏻
> 
> Just a small request:
> 
>     * Please import the `config` from `scr/config.ts` and use `config.app.baseUrl`

I tried importing `./src/config.ts` into `./vite.config.ts`, however this seem to cause issues with the `import.meta.env` variables.

Because `./vite.config.ts` defines `import.meta.env` it seems to a chicken and egg issue, where you can't import `./src/config.ts` into `./vite.config.ts`, until `./vite.config.ts` has defined/loaded it, making `./src/config.ts` unusable in `./vite.config.ts`

**Comment by CorentinTh** [comment]
Yeah you're right, I did not thought of this 🤔 
I added a fallback for the base url 

Thank you for this PR 🙏🏻

**Review by CorentinTh — APPROVED** [review]

**Comment by kurotorakun** [comment]
Hi @CorentinTh , @rmtsrc ,

Can you confirm if the "BASE_URL" env variable can be used while deploying the docker image?
In docker hub register, the nightly version has no mention of it in the dockerfile, neither in the "latest" labelled.

**Comment by rmtsrc** [comment]
I believe that `BASE_URL` is a build time only variable and doesn't work at runtime.

It is possible to build your own Docker image with a custom `BASE_URL`. First you would have to `git clone` this repo then add the following to the Dockerfile:

```Dockerfile
# Add this before "RUN pnpm build"
ARG BASE_URL
ENV BASE_URL=${BASE_URL}
```

Then rebuild and run the container via:

```bash
docker build -t it-tools --build-arg BASE_URL="/my-folder/" .
docker run -d --name it-tools --restart unless-stopped -p 8080:80 it-tools
```

Then if you go to `http://localhost:8080` you'll get a blank page, but opening the DevTools (& refreshing) you'll notice in the Network tab that the app is trying to fetch assets from `/my-folder/...`

So you would need to put another server in front of it, like [Nginx Proxy Manager](https://nginxproxymanager.com/), [Traefik](https://traefik.io/traefik/), [caddy](https://caddyserver.com/) etc. Then setup a reverse proxy pass using `/my-folder`

**Comment by kurotorakun** [comment]
Hi @rmtsrc ,

Thanks for the feedback, and the detailed instructions.

Based on @CorentinTh I got the feeling that the env variable was not expected to work on runtime.
Nevertheless, there are several tools/images than allow this configuration.

@CorentinTh , do you have any plans to implement this feature (BASE_URL on runtime) in the future?
It will be more convenient to be able to do it on runtime than build the docker image after every update.

Thanks in advance,
Marc.

**Comment by veerendra2** [comment]
Hello, Hopefully we get this feature (BASE_URL on runtime) in future. 
Meanwhile I created a handy script to automates the build process.
```bash
$ cat build.sh
#!/usr/bin/env bash

TMP_DIR=$(mktemp -d -t "${1}.XXXXXXX")
LATEST_TAG=$(curl -sS  https://api.github.com/repos/CorentinTh/it-tools/releases/latest | jq -r '.tag_name')

pushd ${TMP_DIR} 1>/dev/null

echo "[*] Download ${TMP_DIR}/${LATEST_TAG}.tar.gz"
curl -sSOL "https://github.com/CorentinTh/it-tools/archive/refs/tags/${LATEST_TAG}.tar.gz"
DIR_NAME=$(tar -tf v2023.8.21-6f93cba.tar.gz | head -1)

echo "[*] Extract ${LATEST_TAG}.tar.gz"
tar -xf ${LATEST_TAG}.tar.gz

pushd $DIR_NAME 1>/dev/null

echo "[*] Update BASE_URL in Dockerfile"
# Update your BASE_URL below!
sed -i '/RUN pnpm build/i ENV BASE_URL="/it-tools/"' Dockerfile

echo "[*] Run docker build"
docker build -t it-tools .

echo "[*] Remove ${TMP_DIR}"
rm -rf ${TMP_DIR}

```

**Comment by YealKio** [comment]
great genius! https://github.com/CorentinTh/it-tools/pull/461#issuecomment-1602506049

**Comment by Majramos** [comment]
Don't you need to add the `ENV BASE_URL="/it-tools/"` to both stages of image build?

I had problems before I added the env variable to the second stage also.

**Comment by sharevb** [comment]
Hi @rmtsrc , @Majramos , @YealKio , @veerendra2 , @kurotorakun , implemented BASE_URL (and config sample) in my fork, if you arr interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

Detailed explaination: https://github.com/sharevb/it-tools?tab=readme-ov-file#docker-compose-for-hosting-in-a-it-tools-subfolder and https://github.com/sharevb/it-tools?tab=readme-ov-file#docker-compose-for-hosting-in-a-it-tools-subfolder

**Pull request merged**
